<center>


    <!--
    <h1>Biography</h1>
    -->

    <p>
        <img class="img-fluid" src="images/Anzeigebild-300x300.png" id="image_biography">
    </p>

<?php if ($lang == "de") { ?>
    
    <p>
        1992 Geboren in Frankfurt am Main, Deutschland
    </p>
    <p>
        2017 Bachelor of Fine Arts in Szenographie (Filmuniversität Babelsberg), Deutschland
    </p>
    <p>
        2020 Klassisch-Realistische Malerei in Florenz, Italien
    </p>
    
<?php } else { ?>
    
    <p>
        1992 Born in Frankfurt am Main, Germany
    </p>
    <p>
        2017 Bachelor of Fine Arts in Production Design (Filmuniversity Babelsberg), Germany
    </p>
    <p>
        2020 Classic Realist Painting in Florence, Italy
    </p>
    
<?php } ?>

    <br>

</center>
