<center>


    <!--
    <h1>Biography</h1>
    -->

    <p>
        <img class="img-fluid" src="images/Anzeigebild-300x300.png" id="image_biography">
    </p>

<?php if ($lang == "de") { ?>
    <p>
        1992 Geboren in Frankfurt am Main
    </p>
    <p>
        2012 Work and Travel in Canada und Alaska
    </p>
    <p>
        2013 European Film College, Dänemark
    </p>
    <p>
        Winter 2014 Erste Reise nach Island
    </p>
    <p>
        2017 Bachelor of Fine Arts in Szenographie an der Filmuniversität Babelsberg
    </p>
    <p>
        2019 Classic Realist Painting in Florenz, Italien
    </p>
<?php } else { ?>
    <p>
        1992 Born in Frankfurt am Main, Germany
    </p>
    <p>
        2012 Work and Travel in Canada and Alaska
    </p>
    <p>
        2013 European Film College, Denmark
    </p>
    <p>
        2014 First Journey to my favorite place on earth – Iceland – in Winter
    </p>
    <p>
        2017 Bachelor of Fine Arts in Production Design at Filmuniversity Babelsberg
    </p>
    <p>
        2019 Classic Realist Painting in Florence, Italy
    </p>
<?php } ?>

    <br>

</center>
