<center>
    <h1><?= ($lang == 'de' ? 'Kontakt' : 'Contact'); ?></h1>
</center>

<?php

$input_name_first = trim($_REQUEST['input_name_first'] ?? '');
$input_name_last = trim($_REQUEST['input_name_last'] ?? '');
$input_email = trim($_REQUEST['input_email'] ?? '');
$input_phone = trim($_REQUEST['input_phone'] ?? '');
$input_message = trim($_REQUEST['input_message'] ?? '');

if ($input_email) {
    $input_name_first = $input_name_first ?: 'Kein Vorname';
    $input_name_last = $input_name_last ?: 'Kein Nachname';
    $input_email = $input_email ?: 'Keine E-Mail';
    $input_phone = $input_phone ?: 'Keine Telefonnummer';
    $input_message = $input_message ?: 'Keine Nachricht';

    $recipients = [
        'info@wintherlanden.com',
        'tobias.schulz@linux.com',
    ];
    foreach ($recipients as $recipient) {
        $subject = 'subject';
        $message = 'Kontaktformular: ' . $input_name_first . ' ' . $input_name_last . ' ' . substr($input_message, 0, 20);
        $headers = array(
            'From' => trim($input_name_first . ' ' . $input_name_last) . ' Kontaktfomular <info@wintherlanden.com>',
            'Reply-To' => ($input_email ?: 'info@wintherlanden.com'),
            'X-Mailer' => 'PHP/' . phpversion()
        );

        mail($recipient, $subject, $message, $headers);
    }

    echo '<center><p>';
    echo ($lang == 'de' ? 'Vielen Dank für Ihre Nachricht.' : 'Your message has been sent.');
    echo '</p>    </center>';

} else {
    ?>

    <form action="?contact" method="post">
        <div class="row">
            <div class="form-group col-md-6">
                <label for="input_name_first"><?= ($lang == 'de' ? 'Vorname' : 'First name'); ?></label>
                <input type="text" class="form-control" id="input_name_first" name="input_name_first"
                       value="<?= htmlspecialchars($input_name_first, ENT_QUOTES, "UTF-8"); ?>" placeholder="" required>
            </div>
            <div class="form-group col-md-6">
                <label for="input_name_last"><?= ($lang == 'de' ? 'Nachname' : 'Last name'); ?></label>
                <input type="text" class="form-control" id="input_name_last" name="input_name_last"
                       value="<?= htmlspecialchars($input_name_last, ENT_QUOTES, "UTF-8"); ?>" placeholder="" required>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label for="input_email">E-Mail</label>
                <input type="email" class="form-control" id="input_email" name="input_email"
                       value="<?= htmlspecialchars($input_email, ENT_QUOTES, "UTF-8"); ?>" placeholder="" required>
            </div>
            <div class="form-group col-md-6">
                <label for="input_phone"><?= ($lang == 'de' ? 'Telefon' : 'Phone'); ?></label>
                <input type="tel" class="form-control" id="input_phone" name="input_phone"
                       value="<?= htmlspecialchars($input_phone, ENT_QUOTES, "UTF-8"); ?>" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="input_message"><?= ($lang == 'de' ? 'Nachricht' : 'Message'); ?></label>
            <textarea type="text" class="form-control" id="input_message" name="input_message" placeholder=""
                      style="height: 200px;"><?= htmlspecialchars($input_message, ENT_QUOTES, "UTF-8"); ?></textarea>
        </div>
        <div class="row">
            <div class="form-group col-md-10">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="input_checkbox" name="input_checkbox">
                    <label class="form-check-label" for="input_checkbox">
                        <?= ($lang == 'de' ? 'Datenschutz: Ich erkläre mich mit der Verarbeitung der eingegebenen Daten sowie der Datenschutzerklärung einverstanden.' : 'I agree with the processing of the entered data as well as the data protection declaration.'); ?>
                    </label>
                </div>
            </div>
            <div class="form-group col-md-2">
                <button type="submit" class="btn btn-primary"
                        style="width: 100%; "><?= ($lang == 'de' ? 'Absenden' : 'Send'); ?></button>
            </div>
        </div>
    </form>

    <?php
}
?>


<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>



