    <h1><?= ($lang == 'de' ? 'Kontakt' : 'Contact'); ?></h1>

    <form>
            <div class="form-group">
                <label for="input_name_first"><?= ($lang == 'de' ? 'Vorname' : 'First name'); ?></label>
                <input type="text" class="form-control" id="input_name_first" placeholder="">
            </div>
            <div class="form-group">
                <label for="input_name_last"><?= ($lang == 'de' ? 'Nachname' : 'Last name'); ?></label>
                <input type="text" class="form-control" id="input_name_last" placeholder="">
            </div>
        <div class="form-group">
            <label for="input_email">E-Mail</label>
            <input type="email" class="form-control" id="input_email" placeholder="">
        </div>
        <div class="form-group">
            <label for="input_phone"><?= ($lang == 'de' ? 'Telefon' : 'Phone'); ?></label>
            <input type="text" class="form-control" id="input_phone" placeholder="">
        </div>
        <div class="form-group">
            <label for="input_message"><?= ($lang == 'de' ? 'Nachricht' : 'Message'); ?></label>
            <textarea type="text" class="form-control" id="input_message" placeholder="" style="height: 100px;">
            </textarea>
        </div>
        <div class="form-group">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="input_checkbox">
                <label class="form-check-label" for="input_checkbox">
                    <?= ($lang == 'de' ? 'Datenschutz: Ich erkläre mich mit der Verarbeitung der eingegebenen Daten sowie der Datenschutzerklärung einverstanden.' : 'Message'); ?>
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
    </form>



