<!--
<center>
    <h1>Gallery</h1>
</center>
-->


<?php

$categories = [

    "Replica" => "Replica",
    "Figure" => "Figure",
    "Cast" => "Cast",
    "Animals" => "Animals",
    "Portrait" => "Portrait",

];

?>

<style>
    .gallery {
        padding: 0px 30px;
    }

    .gallery img.fixed_height {
        width: calc(25% - 4px);
    }

    @media (max-width: 991px) {
        .gallery img.fixed_height {
            width: calc(33.333333333% - 4px);
        }
    }
    @media (max-width: 768px) {
        .gallery img.fixed_height {
            width: calc(33.333333333% - 4px);
        }
    }

    .gallery .row {
        margin-bottom: 18px;
        background: url(images/verlauf.png);
        background-size: 100%;
    }

    .nopad {
        padding-left: 0;
        padding-right: 0;
    }

    .small_padding img {
        padding: 9px 6px;
    }

    .modal-body {
        padding: 0;
    }

    .gallery_scroll {
        overflow-x: hidden;
	position: relative;
    }
    .gallery_scroll2 {
	position: absolute;
	width: 60%;
	top: 0;
	left: 40%;
	height: 100%;
	background: linear-gradient(to right, transparent, rgba(255, 255, 255, 0.55));
	pointer-events: none;
    }

    .pfeil {
        position: absolute;
	right: 0px;
	top: calc(50% - 11px);
    }
    .pfeil:hover {
        cursor: pointer;
    }
    .pfeil img {
        height: 22px;
        margin-right: 15px;
    }

    .pfeil2 {
        position: absolute;
	left: 0px;
	top: calc(50% - 11px);
    }
    .pfeil2:hover {
        cursor: pointer;
    }
    .pfeil2 img {
        height: 22px;
        margin-left: 15px;
	transform: scaleX(-1);
    }
</style>

<div class="gallery">

    <?php
    foreach ($categories as $name => $title) {
        $images = scandir("gallery/" . $name);
        $image_front = null;
        $images_gallery = [];
        foreach ($images as $image) {
            if ($image[0] == '.')
                continue;

            if (strpos($image, "Front") !== false) {
                if (strpos($image, 'Front.' . $lang . '.png') !== false) {
                    $image_front = $image;
                }
            } else {
                $images_gallery[] = $image;
            }
        }
        ?>
        <div class="row">

            <div class="col-lg-2 col-md-3 col-sm-3 nopad">
                <a href="gallery/<?= $name; ?>/<?= $image_front; ?>" data-toggle="lightbox"
                   data-gallery="example-gallery">
                    <img src="thumb.php?src=gallery/<?= $name; ?>/<?= $image_front; ?>" class="img-fluid" style="width: 100%;">
                </a>
            </div>
            <div class="col-lg-10 col-md-9 col-sm-9 nopad">
		<div class="gallery_scroll">
		<nobr>
                <?php
                foreach ($images_gallery as $image) {
                    ?>
                    <a href="gallery/<?= $name; ?>/<?= $image; ?>" data-toggle="lightbox" data-gallery="example-gallery"
                       class="nopad small_padding"><img src="thumb.php?src=gallery/<?= $name; ?>/<?= $image; ?>" class="img-fluid fixed_height"></a>
                    <?php
                }
                ?>
		</nobr>
		</div>
		<div class="gallery_scroll2">
		</div>
		<div class="pfeil">
			<img src="images/pfeil.png">
		</div>
		<div class="pfeil2">
			<img src="images/pfeil.png">
		</div>
            </div>

        </div>
        <?php
    }
    ?>



</div>
