<!--
<center>
    <h1>Gallery</h1>
</center>
-->


<?php

$categories = [

    "Replica" => "Replica",
    "Figure" => "Figure",
    "Cast" => "Cast",
    "Animals" => "Animals",
    "Portrait" => "Portrait",

];

?>

<style>
    .gallery {
        padding: 0px 30px;
    }

    .gallery img.fixed_height {
        width: calc(25% - 4px);
    }

    .gallery .row {
        margin-bottom: 18px;
        background: url(images/verlauf.png);
        background-size: 100%;
    }

    .nopad {
        padding-left: 0;
        padding-right: 0;
    }

    .small_padding img {
        padding: 9px;
    }

    .gallery_scroll {
        overflow-x: auto;
	position: relative;
    }

    .pfeil {
        position: absolute;
	right: 0px;
	top: calc(50% - 22px);
    }
    .pfeil img {
        height: 44px;
    }
</style>

<div class="gallery">

    <?php
    foreach ($categories as $name => $title) {
        $images = scandir("gallery/" . $name);
        $image_front = null;
        $images_gallery = [];
        foreach ($images as $image) {
            if ($image[0] == '.')
                continue;

            if (strpos($image, "Front") !== false) {
                if (strpos($image, 'Front.' . $lang . '.png') !== false) {
                    $image_front = $image;
                }
            } else {
                $images_gallery[] = $image;
                $images_gallery[] = $image;
            }
        }
        ?>
        <div class="row">

            <div class="col-sm-2 nopad">
                <a href="gallery/<?= $name; ?>/<?= $image_front; ?>" data-toggle="lightbox"
                   data-gallery="example-gallery">
                    <img src="thumb.php?src=gallery/<?= $name; ?>/<?= $image_front; ?>" class="img-fluid" style="width: 100%;">
                </a>
            </div>
            <div class="col-sm-10 nopad">
		<div class="gallery_scroll">
		<nobr>
                <?php
                foreach ($images_gallery as $image) {
                    ?>
                    <a href="gallery/<?= $name; ?>/<?= $image; ?>" data-toggle="lightbox" data-gallery="example-gallery"
                       class="col-sm-3 nopad small_padding">
                        <img src="thumb.php?src=gallery/<?= $name; ?>/<?= $image; ?>" class="img-fluid fixed_height">
                    </a>
                    <?php
                }
                ?>
		</nobr>
		</div>
		<div class="pfeil">
			<img src="images/pfeil.png">
		</div>
            </div>

        </div>
        <?php
    }
    ?>


</div>
