<center>

    <p>
        <img class="img-fluid" src="images/Welcome.png" id="image_welcome">
    </p>


<?php if ($lang == "de") { ?>
    
    <p>
        Mit besonderer Leidenschaft für Klassisch-Realistische Malerei<br>
        und inspiriert von Meistern wie Bouguerau, John Singer Sargent und Leighton,<br>
        widmet sich die in Italien ausgebildete Künstlerin<br>
diverser Projekte und Auftragsarbeiten.
     

    <p>
        Ob Portraits, Akte, Stilleben oder Kombinationen derselben,<br>
bringt sie ihre Fähigkeiten zum Ausdruck<br>
und überzeugt sowohl mit technischer Perfektion,<br>
als auch feinfühliger Interpretation der jeweiligen Sujets.
    </p>

    <p>&nbsp;</p>

    <p>
        Für allgemeine Fragen oder Anfragen, nutzen Sie bitte das Kontaktformular.
    </p>

    <p>
        
    </p>

    <p>&nbsp;</p>

    <p>
      
    </p>

    
<?php } else { ?>
    
    <p>
        I am a young artist from Germany whose whole life is lanced by a fascination<br>
        for northern, snowy and silent places.
    </p>

    <p>
        Only imagining this environment gives me a feeling of freedom<br>
        and enhances my creativity.
    </p>

    <p>&nbsp;</p>

    <p>
        In the near future, I aim for travelling north and portraying people<br>
        living in remote, mystic places.
    </p>

    <p>
        Portraiture is a huge passion of mine, since it stokes my continuous ambition<br>
        to transport the magic of each sitters desired expression.
    </p>

    <p>&nbsp;</p>

    <p>
        Feel free to take a look around<br>
        and don‘t hesitate to contact me for any requests!
    </p>

<?php } ?>
    
<!--
    <p>
        Sincerely,
    </p>

    <img class="img-fluid" src="images/Unterschrift.png" id="image_signature">
-->

</center>
