<center>

    <p>
        <img class="img-fluid" src="images/Welcome.png" id="image_welcome">
    </p>


<?php if ($lang == "de") { ?>
    
    <p>
        Mit besonderer Leidenschaft für Klassisch-Realistische Malerei<br>
        und inspiriert von Meistern wie William-Adolphe Bouguerau, John Singer Sargent und Frederic Leighton,<br>
        widmet sich die in Italien ausgebildete Künstlerin<br>
diverser Projekte und Auftragsarbeiten.
        
 <p>&nbsp;</p>
     

    <p>
        Ob Portraits, Akte, Stilleben oder Kombinationen derselben - <br>
mit technischer Perfektion und feinfühliger Interpretation der jeweiligen Sujets<br>
entstehen Gemälde eindrucksvoller Atmosphäre.
   
    </p>

    <p>&nbsp;</p>

    <p>
        Für allgemeine Fragen oder Anfragen, nutzen Sie bitte das Kontaktformular.
    </p>

    <p>
        
    </p>

    <p>&nbsp;</p>

    <p>
      
    </p>

    
<?php } else { ?>
    
    <p>
        With grand passion for Classical Realism<br>
and inspired by masters like William-Adolphe Bouguereau, John Singer Sargent and Frederic Leighton<br>
the in Italy trained artist commits herself to diverse projects and commissions..
    </p>
    
 <p>&nbsp;</p>

    <p>
        Whether considering Portraits, Figurative works, Stillifes or combinations of those,<br>
 she enhances her skills and stands out with technical perfection<br>
as well as  delicate interpretation of the respective sujet.
    </p>

    <p>&nbsp;</p>

    <p>
        For any questions or requests on commissions, please use the contact form.
    </p>

    <p>
        
    </p>

    <p>&nbsp;</p>

    <p>
        
    </p>

<?php } ?>
    
<!--
    <p>
        Sincerely,
    </p>

    <img class="img-fluid" src="images/Unterschrift.png" id="image_signature">
-->

</center>
