<center>

    <p>
        <img class="img-fluid" src="images/Welcome.png" id="image_welcome">
    </p>


    <p>
        I am a young artist from Germany whose whole life is lanced by a fascination<br>
        for northern, snowy and silent places.
    </p>

    <p>
        Only imagining this environment gives me a feeling of freedom<br>
        and enhances my creativity.
    </p>

    <p>&nbsp;</p>

    <p>
        In the near future, I aim for travelling north and portraying people<br>
        living in remote, mystic places.
    </p>

    <p>
        Portraiture is a huge passion of mine, since it stokes my continuous ambition<br>
        to transport the magic of each sitters desired expression.
    </p>

    <p>&nbsp;</p>

    <p>
        Feel free to take a look around<br>
        and don‘t hesitate to contact me for any requests!
    </p>


    <p>
        Sincerely,
    </p>


    <img class="img-fluid" src="images/Unterschrift.png" id="image_signature">

</center>
