<!--
<center>
    <h1>Instagram</h1>
</center>
-->


<?php

function store_instagram()
{
    $instagram_directory = __DIR__ . '/instagram-api/';
    @mkdir($instagram_directory);

    $instagram_html = file_get_contents('instagram.inc.php');

    $instagram_html = explode('window._sharedData =', $instagram_html)[1];
    $instagram_html = explode(';</script', $instagram_html)[0];

    $instagram_json = json_decode($instagram_html);

    $instagram_edges = $instagram_json->entry_data->ProfilePage[0]->graphql->user->edge_owner_to_timeline_media->edges;

    foreach ($instagram_edges as $instagram_edge) {
        $shortcode = $instagram_edge->node->shortcode;
        $json_new = json_encode($instagram_edge);
        $json_old = is_file($instagram_directory . $shortcode) ? file_get_contents($instagram_directory . $shortcode) : '';
        if ($json_new != $json_old) {
            file_put_contents($instagram_directory . $shortcode, json_encode($instagram_edge));
            if (!is_file($instagram_directory . $shortcode)) {
                echo 'Konnte Instagram-Bild nicht speichern: ' . $shortcode . '<br>';
            }
        }
    }
}

/**
 * @return array
 */
function load_instagram()
{
    $instagram_directory = __DIR__ . '/instagram-api/';
    @mkdir($instagram_directory);

    $instagram_edges = [];

    $files = scandir($instagram_directory);
    foreach ($files as $file) {
        if (strlen($file) >= 3) {
            $a = json_decode(file_get_contents($instagram_directory . $file));
            foreach ($a as $item) {
                $instagram_edges[] = $item;
            }
        }
    }

    usort($instagram_edges, function ($a, $b) {
        return $b->taken_at_timestamp - $a->taken_at_timestamp;
    });

    return $instagram_edges;
}

store_instagram();
$instagram_edges = load_instagram();

# echo '<pre>' . json_encode($instagram_edges, JSON_PRETTY_PRINT) . '</pre>';

?>

<style>
    .instagram {
        padding: 30px;
    }

    .instagram img {
        margin-bottom: 10px;
    }

    .small_padding {
        padding-left: 7px;
        padding-right: 5px;
    }

</style>

<div class="instagram">

    <div class="row">
        <div class="col-xs-0 col-md-2">
        </div>

        <div class="col-xs-12 col-md-8">
            <div class="row">


                <?php
                foreach ($instagram_edges as $instagram_edge) {
                    $shortcode = $instagram_edge->shortcode;
                    $edge_text = $instagram_edge->edge_media_to_caption->edges[0]->node->text;
                    ?>

                    <div class="col-sm-4 small_padding">

                        <a href="https://www.instagram.com/p/<?= $shortcode; ?>" data-toggle="lightbox"
                           data-gallery="example-gallery" data-type="instagram"
                           class="nopad">
                            <img src="<?= $instagram_edge->thumbnail_src; ?>" class="img-fluid">
                        </a>
                    </div>
                    <?php
                }
                ?>

            </div>
        </div>
    </div>


</div>
