<center>
    <h1>Instagram</h1>
</center>


<?php

$instagram_html = file_get_contents('instagram.inc.php');

$instagram_html = explode('window._sharedData =', $instagram_html)[1];
$instagram_html = explode(';</script', $instagram_html)[0];

$json = json_decode($instagram_html);

$edges = $json->entry_data->ProfilePage[0]->graphql->user->edge_owner_to_timeline_media->edges;

echo '<pre>' . json_encode($edges, JSON_PRETTY_PRINT) . '</pre>';

$categories = [

    "Replica" => "Replica",
"Figure" => "Figure",
"Cast" => "Cast",
"Animals" => "Animals",
"Portrait" => "Portrait",

];

?>

<style>
    .gallery img {
        height: 212px;
    }

    .gallery .row {
        margin-bottom: 10px;
    }

    .nopad {
        padding-left: 0;
        padding-right: 0;
    }
</style>

<div class="gallery">

    <div class="row">

        <div class="col-sm-12 nopad">
            <?php
                foreach ($edges as $edge)
                {
                    ?>
            <a href="gallery/<?=$name;?>/<?=$image;?>" data-toggle="lightbox" data-gallery="example-gallery"
               class="col-sm-3 nopad">
                <img src="gallery/<?=$name;?>/<?=$image;?>" class="img-fluid">
            </a>
            <?php
                }
                ?>
        </div>

    </div>


</div>
